services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/img_quality_eval

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=img_quality_eval
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6

  celery:
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A img_quality_eval worker --loglevel=warning
    #command: celery -A img_quality_eval worker --loglevel=warning
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/img_quality_eval
      - AWS_ACCESS_KEY_ID=${TIGRIS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${TIGRIS_SECRET_ACCESS_KEY:-}

volumes:
  postgres_data:
